/* The following code was generated by JFlex 1.4.1 on 13/8/26, 19:54 */

package org.example.MatchColors;
import java.io.*;
import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 13/8/26, 19:54 from the specification file
 * <tt>CodexLatinusColorsLenguaje.jflex</tt>
 */
public class ColorsLenguaje extends AbstractJFlexCTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int MLC = 1;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\11\1\12\1\0\1\11\1\7\22\0\1\11\1\65\1\4"+
    "\1\10\1\0\1\6\1\66\1\3\2\15\1\63\1\61\1\15\1\62"+
    "\1\14\1\13\12\2\2\15\1\40\1\64\1\41\1\6\1\0\1\43"+
    "\1\46\2\1\1\50\1\56\2\1\1\45\2\1\1\47\1\52\1\54"+
    "\1\55\1\57\1\1\1\44\1\51\1\1\1\53\1\42\4\1\1\15"+
    "\1\5\1\15\1\6\1\1\1\0\1\25\1\37\1\33\1\27\1\20"+
    "\1\32\1\35\1\1\1\24\2\1\1\26\1\31\1\16\1\17\1\34"+
    "\1\1\1\23\1\21\1\22\1\30\1\60\1\1\1\36\2\1\1\15"+
    "\1\67\1\15\1\6\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\1\3\1\4\1\5\1\1\1\6"+
    "\1\5\1\7\1\10\14\1\2\7\4\1\4\7\3\1"+
    "\3\11\1\12\1\13\1\0\1\3\1\14\1\3\1\15"+
    "\2\4\1\16\1\17\5\1\1\20\14\1\1\21\5\1"+
    "\1\22\1\23\1\24\1\25\16\1\1\20\23\1\1\26"+
    "\11\1\1\21\10\1\1\27\17\1";

  private static int [] zzUnpackAction() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\u0118\0\u0150\0\u0188"+
    "\0\u01c0\0\u01f8\0\160\0\u0230\0\160\0\u0268\0\u02a0\0\u02d8"+
    "\0\u0310\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498"+
    "\0\u04d0\0\u0508\0\u0540\0\u0578\0\u05b0\0\u05e8\0\u0620\0\u0658"+
    "\0\u0690\0\160\0\u06c8\0\u06c8\0\u0700\0\u0738\0\u0770\0\u07a8"+
    "\0\u07e0\0\160\0\u0818\0\u0850\0\u0888\0\160\0\u08c0\0\160"+
    "\0\u08f8\0\u0930\0\160\0\u0968\0\u09a0\0\u09d8\0\u0a10\0\u0a48"+
    "\0\u0a80\0\250\0\u0ab8\0\u0af0\0\u0b28\0\u0b60\0\u0b98\0\u0bd0"+
    "\0\u0c08\0\u0c40\0\u0c78\0\u0cb0\0\u0ce8\0\u0d20\0\160\0\u0d58"+
    "\0\u0d90\0\u0dc8\0\u0e00\0\u0e38\0\160\0\u0e70\0\160\0\160"+
    "\0\u0ea8\0\u0ee0\0\u0f18\0\u0f50\0\u0f88\0\u0fc0\0\u0ff8\0\u1030"+
    "\0\u1068\0\u10a0\0\u10d8\0\u1110\0\u1148\0\u1180\0\u11b8\0\u11f0"+
    "\0\u1228\0\u1260\0\u1298\0\u12d0\0\u1308\0\u1340\0\u1378\0\u13b0"+
    "\0\u13e8\0\u1420\0\u1458\0\u1490\0\u14c8\0\u1500\0\u1538\0\u1570"+
    "\0\u15a8\0\u15e0\0\250\0\u1618\0\u1650\0\u1688\0\u16c0\0\u16f8"+
    "\0\u1730\0\u1768\0\u17a0\0\u17d8\0\250\0\u1810\0\u1848\0\u1880"+
    "\0\u18b8\0\u18f0\0\u1928\0\u1960\0\u1998\0\250\0\u19d0\0\u1a08"+
    "\0\u1a40\0\u1a78\0\u1ab0\0\u1ae8\0\u1b20\0\u1b58\0\u1b90\0\u1bc8"+
    "\0\u1c00\0\u1c38\0\u1c70\0\u1ca8\0\u1ce0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\2\3\1\10\1\11"+
    "\1\12\1\13\1\14\2\15\1\16\1\4\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\2\4\1\27"+
    "\1\4\1\30\2\4\1\31\1\32\1\33\1\34\7\4"+
    "\1\35\3\4\1\36\1\4\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\7\47\1\50\1\51\1\47"+
    "\1\52\55\47\71\0\2\4\13\0\22\4\2\0\17\4"+
    "\7\0\2\53\1\5\2\0\1\53\2\0\1\53\3\0"+
    "\1\54\1\0\22\53\2\0\17\53\7\0\3\55\1\56"+
    "\1\55\1\57\1\55\1\0\2\55\1\0\55\55\4\7"+
    "\1\60\1\61\1\7\1\62\2\7\1\62\55\7\12\0"+
    "\1\13\65\0\1\63\70\0\1\12\71\0\1\64\55\0"+
    "\2\4\13\0\1\4\1\65\10\4\1\66\7\4\2\0"+
    "\17\4\10\0\2\4\13\0\3\4\1\67\16\4\2\0"+
    "\17\4\10\0\2\4\13\0\2\4\1\70\1\4\1\71"+
    "\1\4\1\72\13\4\2\0\17\4\10\0\2\4\13\0"+
    "\2\4\1\73\17\4\2\0\17\4\10\0\2\4\13\0"+
    "\2\4\1\74\4\4\1\75\12\4\2\0\17\4\10\0"+
    "\2\4\13\0\1\76\21\4\2\0\17\4\10\0\2\4"+
    "\13\0\10\4\1\77\4\4\1\75\4\4\2\0\17\4"+
    "\10\0\2\4\13\0\6\4\1\100\13\4\2\0\17\4"+
    "\10\0\2\4\13\0\2\4\1\101\7\4\1\102\7\4"+
    "\2\0\17\4\10\0\2\4\13\0\6\4\1\103\1\104"+
    "\12\4\2\0\17\4\10\0\2\4\13\0\2\4\1\105"+
    "\17\4\2\0\17\4\10\0\2\4\13\0\1\4\1\106"+
    "\20\4\2\0\17\4\47\0\1\107\23\0\1\42\44\0"+
    "\1\107\22\0\1\42\4\0\2\4\13\0\22\4\2\0"+
    "\1\4\1\110\15\4\10\0\2\4\13\0\22\4\2\0"+
    "\1\4\1\111\7\4\1\112\5\4\10\0\2\4\13\0"+
    "\22\4\2\0\3\4\1\113\13\4\10\0\2\4\13\0"+
    "\2\4\1\114\17\4\2\0\17\4\70\0\1\42\70\0"+
    "\1\42\71\0\1\42\71\0\1\42\70\0\1\42\10\47"+
    "\1\0\1\47\1\0\65\47\1\0\1\47\1\52\55\47"+
    "\10\0\1\115\57\0\3\53\2\0\1\53\2\0\1\53"+
    "\5\0\22\53\2\0\17\53\11\0\1\116\65\0\3\57"+
    "\1\117\3\57\1\0\2\57\1\0\60\57\1\56\3\57"+
    "\1\0\2\57\1\0\55\57\12\7\1\0\55\7\4\0"+
    "\1\120\63\0\12\64\1\0\55\64\1\0\2\4\13\0"+
    "\1\72\21\4\2\0\17\4\10\0\2\4\13\0\13\4"+
    "\1\121\6\4\2\0\17\4\10\0\2\4\13\0\4\4"+
    "\1\122\15\4\2\0\17\4\10\0\2\4\13\0\5\4"+
    "\1\123\14\4\2\0\17\4\10\0\2\4\13\0\5\4"+
    "\1\124\14\4\2\0\17\4\10\0\2\4\13\0\20\4"+
    "\1\125\1\4\2\0\17\4\10\0\2\4\13\0\11\4"+
    "\1\126\10\4\2\0\17\4\10\0\2\4\13\0\4\4"+
    "\1\127\15\4\2\0\17\4\10\0\2\4\13\0\4\4"+
    "\1\130\15\4\2\0\17\4\10\0\2\4\13\0\6\4"+
    "\1\131\13\4\2\0\17\4\10\0\2\4\13\0\4\4"+
    "\1\132\15\4\2\0\17\4\10\0\2\4\13\0\15\4"+
    "\1\133\4\4\2\0\17\4\10\0\2\4\13\0\13\4"+
    "\1\72\6\4\2\0\17\4\10\0\2\4\13\0\1\134"+
    "\21\4\2\0\17\4\10\0\2\4\13\0\10\4\1\135"+
    "\4\4\1\136\4\4\2\0\17\4\10\0\2\4\13\0"+
    "\5\4\1\137\14\4\2\0\17\4\10\0\2\4\13\0"+
    "\1\4\1\140\20\4\2\0\17\4\10\0\2\4\13\0"+
    "\22\4\2\0\2\4\1\141\14\4\10\0\2\4\13\0"+
    "\22\4\2\0\3\4\1\142\13\4\10\0\2\4\13\0"+
    "\22\4\2\0\12\4\1\143\4\4\10\0\2\4\13\0"+
    "\22\4\2\0\12\4\1\144\4\4\10\0\2\4\13\0"+
    "\5\4\1\145\14\4\2\0\17\4\7\0\2\53\1\116"+
    "\2\0\1\53\2\0\1\53\5\0\22\53\2\0\17\53"+
    "\10\0\2\4\13\0\2\4\1\146\17\4\2\0\17\4"+
    "\10\0\2\4\13\0\1\4\1\72\20\4\2\0\17\4"+
    "\10\0\2\4\13\0\6\4\1\147\13\4\2\0\17\4"+
    "\10\0\2\4\13\0\12\4\1\150\7\4\2\0\17\4"+
    "\10\0\2\4\13\0\4\4\1\151\15\4\2\0\17\4"+
    "\10\0\2\4\13\0\11\4\1\136\10\4\2\0\17\4"+
    "\10\0\2\4\13\0\6\4\1\152\13\4\2\0\17\4"+
    "\10\0\2\4\13\0\2\4\1\153\17\4\2\0\17\4"+
    "\10\0\2\4\13\0\4\4\1\154\15\4\2\0\17\4"+
    "\10\0\2\4\13\0\4\4\1\155\15\4\2\0\17\4"+
    "\10\0\2\4\13\0\6\4\1\156\13\4\2\0\17\4"+
    "\10\0\2\4\13\0\6\4\1\157\13\4\2\0\17\4"+
    "\10\0\2\4\13\0\3\4\1\160\16\4\2\0\17\4"+
    "\10\0\2\4\13\0\2\4\1\161\17\4\2\0\17\4"+
    "\10\0\2\4\13\0\17\4\1\162\2\4\2\0\17\4"+
    "\10\0\2\4\13\0\10\4\1\163\11\4\2\0\17\4"+
    "\10\0\2\4\13\0\22\4\2\0\3\4\1\164\13\4"+
    "\10\0\2\4\13\0\22\4\2\0\13\4\1\165\3\4"+
    "\10\0\2\4\13\0\22\4\2\0\6\4\1\166\10\4"+
    "\10\0\2\4\13\0\22\4\2\0\3\4\1\167\13\4"+
    "\10\0\2\4\13\0\12\4\1\170\7\4\2\0\17\4"+
    "\10\0\2\4\13\0\5\4\1\171\14\4\2\0\17\4"+
    "\10\0\2\4\13\0\2\4\1\172\17\4\2\0\17\4"+
    "\10\0\2\4\13\0\15\4\1\173\4\4\2\0\17\4"+
    "\10\0\2\4\13\0\12\4\1\174\7\4\2\0\17\4"+
    "\10\0\2\4\13\0\1\4\1\175\20\4\2\0\17\4"+
    "\10\0\2\4\13\0\5\4\1\176\14\4\2\0\17\4"+
    "\10\0\2\4\13\0\2\4\1\177\17\4\2\0\17\4"+
    "\10\0\2\4\13\0\2\4\1\200\17\4\2\0\17\4"+
    "\10\0\2\4\13\0\13\4\1\201\6\4\2\0\17\4"+
    "\10\0\2\4\13\0\3\4\1\175\16\4\2\0\17\4"+
    "\10\0\2\4\13\0\12\4\1\202\7\4\2\0\17\4"+
    "\10\0\2\4\13\0\5\4\1\162\14\4\2\0\17\4"+
    "\10\0\2\4\13\0\2\4\1\72\17\4\2\0\17\4"+
    "\10\0\2\4\13\0\22\4\2\0\1\4\1\203\15\4"+
    "\10\0\2\4\13\0\22\4\2\0\2\4\1\175\14\4"+
    "\10\0\2\4\13\0\22\4\2\0\2\4\1\204\14\4"+
    "\10\0\2\4\13\0\22\4\2\0\7\4\1\205\7\4"+
    "\10\0\2\4\13\0\13\4\1\206\6\4\2\0\17\4"+
    "\10\0\2\4\13\0\12\4\1\207\7\4\2\0\17\4"+
    "\10\0\2\4\13\0\3\4\1\72\16\4\2\0\17\4"+
    "\10\0\2\4\13\0\4\4\1\210\15\4\2\0\17\4"+
    "\10\0\2\4\13\0\13\4\1\163\6\4\2\0\17\4"+
    "\10\0\2\4\13\0\5\4\1\211\14\4\2\0\17\4"+
    "\10\0\2\4\13\0\5\4\1\72\14\4\2\0\17\4"+
    "\10\0\2\4\13\0\5\4\1\212\14\4\2\0\17\4"+
    "\10\0\2\4\13\0\7\4\1\213\12\4\2\0\17\4"+
    "\10\0\2\4\13\0\3\4\1\206\16\4\2\0\17\4"+
    "\10\0\2\4\13\0\22\4\2\0\4\4\1\214\12\4"+
    "\10\0\2\4\13\0\22\4\2\0\1\4\1\175\15\4"+
    "\10\0\2\4\13\0\22\4\2\0\11\4\1\215\5\4"+
    "\10\0\2\4\13\0\3\4\1\163\16\4\2\0\17\4"+
    "\10\0\2\4\13\0\12\4\1\216\7\4\2\0\17\4"+
    "\10\0\2\4\13\0\12\4\1\217\7\4\2\0\17\4"+
    "\10\0\2\4\13\0\7\4\1\163\12\4\2\0\17\4"+
    "\10\0\2\4\13\0\10\4\1\220\11\4\2\0\17\4"+
    "\10\0\2\4\13\0\22\4\2\0\3\4\1\221\13\4"+
    "\10\0\2\4\13\0\22\4\2\0\15\4\1\175\1\4"+
    "\10\0\2\4\13\0\5\4\1\222\14\4\2\0\17\4"+
    "\10\0\2\4\13\0\13\4\1\223\6\4\2\0\17\4"+
    "\10\0\2\4\13\0\6\4\1\207\13\4\2\0\17\4"+
    "\10\0\2\4\13\0\22\4\2\0\5\4\1\224\11\4"+
    "\10\0\2\4\13\0\7\4\1\175\12\4\2\0\17\4"+
    "\10\0\2\4\13\0\16\4\1\162\3\4\2\0\17\4"+
    "\10\0\2\4\13\0\22\4\2\0\6\4\1\225\10\4"+
    "\10\0\2\4\13\0\22\4\2\0\7\4\1\175\7\4"+
    "\7\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7448];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\7\1\1\11\1\1\1\11\24\1\1\11"+
    "\7\1\1\11\1\1\1\0\1\1\1\11\1\1\1\11"+
    "\2\1\1\11\23\1\1\11\5\1\1\11\1\1\2\11"+
    "\105\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
   public ColorsLenguaje() {
   }

   private void addHyperlinkToken(int start, int end, int tokenType) {
      int so = start + offsetShift;
      addToken(zzBuffer, start, end, tokenType, so, true);
   }

   private void addToken(int tokenType) {
      addToken(zzStartRead, zzMarkedPos-1, tokenType);
   }

   private void addToken(int start, int end, int tokenType) {
      int so = start + offsetShift;
      addToken(zzBuffer, start, end, tokenType, so, false);
   }

   public void addToken(char[] array, int start, int end, int tokenType,
                  int startOffset, boolean hyperlink) {
      super.addToken(array, start, end, tokenType, startOffset, hyperlink);
      zzStartRead = zzMarkedPos;
   }

   public String[] getLineCommentStartAndEnd() {
      return new String[] { "//", null };
   }

   public Token getTokenList(Segment text, int initialTokenType, int startOffset) {

      resetTokenList();
      this.offsetShift = -text.offset + startOffset;

      int state = Token.NULL;
      switch (initialTokenType) {
                  case Token.COMMENT_MULTILINE:
            state = MLC;
            start = text.offset;
            break;

         default:
            state = Token.NULL;
      }

      s = text;
      try {
         yyreset(zzReader);
         yybegin(state);
         return yylex();
      } catch (IOException ioe) {
         ioe.printStackTrace();
         return new TokenImpl();
      }

   }

   private boolean zzRefill() {
      return zzCurrentPos >= s.offset + s.count;
   }

   public final void yyreset(Reader reader) {
      zzBuffer = s.array;
      zzStartRead = s.offset;
      zzEndRead = zzStartRead + s.count - 1;
      zzCurrentPos = zzMarkedPos = zzPushbackPos = s.offset;
      zzLexicalState = YYINITIAL;
      zzReader = reader;
      zzAtBOL  = true;
      zzAtEOF  = false;
   }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ColorsLenguaje(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public ColorsLenguaje(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 168) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */



  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 5: 
          { addNullToken(); return firstToken;
          }
        case 24: break;
        case 20: 
          { addToken(Token.LITERAL_CHAR);
          }
        case 25: break;
        case 14: 
          { start = zzMarkedPos-2; yybegin(MLC);
          }
        case 26: break;
        case 6: 
          { addToken(Token.WHITESPACE);
          }
        case 27: break;
        case 21: 
          { addToken(Token.ERROR_STRING_DOUBLE);
          }
        case 28: break;
        case 19: 
          { addToken(Token.LITERAL_NUMBER_FLOAT);
          }
        case 29: break;
        case 16: 
          { addToken(Token.RESERVED_WORD);
          }
        case 30: break;
        case 8: 
          { addToken(Token.SEPARATOR);
          }
        case 31: break;
        case 1: 
          { addToken(Token.IDENTIFIER);
          }
        case 32: break;
        case 3: 
          { addToken(Token.ERROR_CHAR); addNullToken(); return firstToken;
          }
        case 33: break;
        case 17: 
          { addToken(Token.FUNCTION);
          }
        case 34: break;
        case 4: 
          { addToken(Token.ERROR_STRING_DOUBLE); addNullToken(); return firstToken;
          }
        case 35: break;
        case 22: 
          { addToken(Token.DATA_TYPE);
          }
        case 36: break;
        case 18: 
          { yybegin(YYINITIAL); addToken(start,zzStartRead+2-1, Token.COMMENT_MULTILINE);
          }
        case 37: break;
        case 12: 
          { addToken(Token.ERROR_CHAR);
          }
        case 38: break;
        case 23: 
          { addToken(Token.LITERAL_BOOLEAN);
          }
        case 39: break;
        case 13: 
          { addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
          }
        case 40: break;
        case 15: 
          { addToken(Token.COMMENT_EOL); addNullToken(); return firstToken;
          }
        case 41: break;
        case 11: 
          { addToken(Token.ERROR_NUMBER_FORMAT);
          }
        case 42: break;
        case 2: 
          { addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
          }
        case 43: break;
        case 7: 
          { addToken(Token.OPERATOR);
          }
        case 44: break;
        case 9: 
          { 
          }
        case 45: break;
        case 10: 
          { addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
          }
        case 46: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 150: break;
            case MLC: {
              addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
            }
            case 151: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
